#!/bin/bash

# 取得する解像度を決める
define_resolution_settings() {
    resolution_1="<mode>" #displayplacer listで調べる
    resolution_2="<mode>" ##displayplacer listで調べる
    resolution_3="<mode>" ##displayplacer listで調べる
}

# 解像度設定選択を決める
show_resolution_settings() {
    echo "Available resolution settings:"
    echo "1. **** × ****" #ターミナルに表示される文字
    echo "2. **** × ****" #ターミナルに表示される文字
    echo "3. **** × ****" #ターミナルに表示される文字
}

# 解像度を変更する関数
change_resolution() {
    selected_resolution=$1
    case $selected_resolution in
        1)
            displayplacer "id:<ディスプレイid> mode:$resolution_1"
            echo "Display resolution changed to $resolution_1"
            ;;
        2)
            displayplacer "id:<ディスプレイid> mode:$resolution_2"
            echo "Display resolution changed to $resolution_2"
            ;;
        3)
            displayplacer "id:<ディスプレイid> mode:$resolution_3"
            echo "Display resolution changed to $resolution_3"
            ;;
        *)
            echo "Invalid selection. Exiting."
            exit 1
            ;;
    esac
}

# 解像度設定を定義する
define_resolution_settings

# 使用可能な解像度設定を表示する
show_resolution_settings

# 解像度を取得し、ターミナルに解像度の選択肢を表示する
read -p "Select a resolution setting (1/2/3): " choice

# 選択した解像度を表示する
change_resolution $choice